### ISSUE TITLE
Add global keyboard shortcuts for toggling controllers from inside a game

### ISSUE THREAD

**Issue by imedox** [ssg/NoJoy#4]
Hi, Great Work and it so help full Thanks you for the App.
If you Can Add shortcut for gamepad to enable it or disable even the application are not focused or minimized, like if i have 3 xbox 360 gamepad wen i press Ctrl+1 it disable gamepad Number 1, if press Alt+1 it activated gamepad Number 1...Ctrl+2 disable gamepad Number 2 ...ex
with option give as to select key for the shortcut we want for all connect game pad one by one for gamepad 1.2.3....
Thanks You.
Edit: not Work on game wen turn off the controller, The Controller stil work on game :(

**Comment by ssg** [comment]
Thanks for the suggestion! I haven't tested this on a Xbox controller, let me work on that first. :)

**Comment by imedox** [comment]
i have 3 wired xbox 360 controller and one wired  Xbox One. if you can test this2 model it will be cool. 
Thank you.

**Comment by ssg** [comment]
@imedox Unfortunately, Xbox's driver (xinputhid.sys) requires a restart when disabled which kills the purpose of having such a driver. So, I probably won't be able to fix that problem soon (a viable solution requires a custom device driver).

**Comment by imedox** [comment]
@ssg way not just block input from be used, it just suggestion.
Thanks.

**Comment by ssg** [comment]
@imedox Blocking input involves a greater undertaking like writing a filter driver and whatnot. I prefer not doing that at the moment. We can revisit this feature if we ever achieve such a driver based approach. Closing this for now. Thanks!
