### ISSUE TITLE
New computer install, crashes when disabling contoller

### ISSUE THREAD

**Issue by MalicT** [ssg/NoJoy#6]
I have used this program for years, it works amazing, the computer is physically in a different room, so being able to disable multiple flight sticks before playing some games is a godsend.

However, I built a new computer, and when I go to disable the controllers, you press a button, and it just crashes, and the controller stays active.

I have used those "all in one" dependency installers, but is there some debug file that I can look at when it crashes to identify why it closes itself and fix it?

**Comment by ssg** [comment]
Hi! What's the configuration (OS version, brand/model of the sticks)? Do you see an error during the crash or does the app just stop responding?

**Comment by MalicT** [comment]
Windows 10 Education (Same as previous computer that worked fine)

When I do it, and open windows event viewer, I get the following two errors at the time stamp of it closing itself:


Faulting application name: NoJoy.exe, version: 0.2.2.0, time stamp: 0x5b7e2ce3
Faulting module name: KERNELBASE.dll, version: 10.0.19041.3086, time stamp: 0xccf81cdd
Exception code: 0xe0434352
Fault offset: 0x0013d8a2
Faulting process id: 0x20590
Faulting application start time: 0x01d9b436d7e41ef7
Faulting application path: C:\Users\Game-PC 20230518\Desktop\NoJoy.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 88442d93-193d-4e50-9306-eb301a749011
Faulting package full name: 
Faulting package-relative application ID: 

I thought that the KERNELBASE.dll might be corrupt, and even tried copying it over from the previous computer, but still no luck.


Application: NoJoy.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at System.Linq.Enumerable.First[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at NoJoy.PowerShell.RunElevated(System.String)
   at NoJoy.GameController+<>c__DisplayClass28_0.<changeStateInBackground>b__0(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by ssg** [comment]
So, I drafted a new release (0.2.3) that should fix the crash, but I don't think that's the main issue. it seems like the "Disable-PnPDevice" and "Enable-PnpDevice" cmdlets in PowerShell are failing for some reason. Can you try running those commands manually and see what error they generate?

**Comment by MalicT** [comment]
My limited knowledge looks at those words and has no idea what to do with it.  Ive googled powershell and tired to do things with it, but again, am afraid I am doing something wrong, and I cant test the new release as I dont know how to compile it

**Comment by ssg** [comment]
@MalicT oops, of course not. I forgot to attach new binaries in the release. You now should be able to download the binary package and test it out.

For the PowerShell part, don't worry about it yet and see how this works out for you.

**Comment by MalicT** [comment]
I can click the buttons and it does not crash, but I get this error message on everything

[X] Error
-no error message generated-

Screenshot:  [https://i.imgur.com/mxwLNkJ.png](https://i.imgur.com/mxwLNkJ.png )

The below is a single button press and all the errors it generates, I currently have five game controllers that windows sees.

 Event viewer errors:

1)

> Engine state is changed from None to Available. 
> 
> Details: 
> 	NewEngineState=Available
> 	PreviousEngineState=None
> 
> 	SequenceNumber=13
> 
> 	HostName=ConsoleHost
> 	HostVersion=5.1.19041.3031
> 	HostId=54281e4e-ed50-4da3-bfc8-dda84aba4ec3
> 	HostApplication=C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive -Command Disable-PnpDevice -InformationAction SilentlyContinue -PassThru -Confirm:$false -InstanceId 'HID\VID_16C0&PID_05BA\B&2FA006C2&0&0000' 2>&1 > C:\Users\Game-PC 20230518\AppData\Local\Temp\tmp772B.tmp
> 	EngineVersion=5.1.19041.3031
> 	RunspaceId=602aec25-7290-405e-b451-0c6234d378c6
> 	PipelineId=
> 	CommandName=
> 	CommandType=
> 	ScriptName=
> 	CommandPath=
> 	CommandLine=

2)

> Engine state is changed from Available to Stopped. 
> 
> Details: 
> 	NewEngineState=Stopped
> 	PreviousEngineState=Available
> 
> 	SequenceNumber=16
> 
> 	HostName=ConsoleHost
> 	HostVersion=5.1.19041.3031
> 	HostId=54281e4e-ed50-4da3-bfc8-dda84aba4ec3
> 	HostApplication=C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive -Command Disable-PnpDevice -InformationAction SilentlyContinue -PassThru -Confirm:$false -InstanceId 'HID\VID_16C0&PID_05BA\B&2FA006C2&0&0000' 2>&1 > C:\Users\Game-PC 20230518\AppData\Local\Temp\tmp772B.tmp
> 	EngineVersion=5.1.19041.3031
> 	RunspaceId=602aec25-7290-405e-b451-0c6234d378c6
> 	PipelineId=
> 	CommandName=
> 	CommandType=
> 	ScriptName=
> 	CommandPath=
> 	CommandLine=

The last set has 6 in it, will post the oldest one, and then only the lines that changed. Screenshot: [https://i.imgur.com/FIBIHr7.png](https://i.imgur.com/FIBIHr7.png)

> Provider "Registry" is Started. 
> 
> Details: 
> 	ProviderName=Registry
> 	NewProviderState=Started
> 
> 	SequenceNumber=1
> 
> 	HostName=ConsoleHost
> 	HostVersion=5.1.19041.3031
> 	HostId=54281e4e-ed50-4da3-bfc8-dda84aba4ec3
> 	HostApplication=C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive -Command Disable-PnpDevice -InformationAction SilentlyContinue -PassThru -Confirm:$false -InstanceId 'HID\VID_16C0&PID_05BA\B&2FA006C2&0&0000' 2>&1 > C:\Users\Game-PC 20230518\AppData\Local\Temp\tmp772B.tmp
> 	EngineVersion=
> 	RunspaceId=
> 	PipelineId=
> 	CommandName=
> 	CommandType=
> 	ScriptName=
> 	CommandPath=
> 	CommandLine=

> Provider "Alias" is Started. 
> 
> Details: 
> 	ProviderName=Alias
> 	NewProviderState=Started
> 
> 	SequenceNumber=3

> Provider "Environment" is Started. 
> 
> Details: 
> 	ProviderName=Environment
> 	NewProviderState=Started
> 
> 	SequenceNumber=5

> Provider "FileSystem" is Started. 
> 
> Details: 
> 	ProviderName=FileSystem
> 	NewProviderState=Started
> 
> 	SequenceNumber=7

> Provider "Function" is Started. 
> 
> Details: 
> 	ProviderName=Function
> 	NewProviderState=Started
> 
> 	SequenceNumber=9

> Provider "Variable" is Started. 
> 
> Details: 
> 	ProviderName=Variable
> 	NewProviderState=Started
> 
> 	SequenceNumber=11


Thank for your help with this.  Is one of the annoying things, I understand some things with computers to be a danger to myself, but getting into PowerShell is one of those untouched things

**Comment by ssg** [comment]
@MalicT Can you try the latest 0.3.0 release? It should work without problems this time. :) It requires 64-bit Windows though.

**Comment by MalicT** [comment]
Installed, and is working, thank you so much for doing this!
